###
POST https://628b9617667aea3a3e3289a2.mockapi.io/api/courses
Content-Type: application/json

{
    "name": "C# .NET",
    "lastName": "40"
}
###
POST https://628b9617667aea3a3e3289a2.mockapi.io/api/courses
Content-Type: application/json

{
    "name": "C# .NET",
    "hours": 40
}
###
POST https://628b9617667aea3a3e3289a2.mockapi.io/api/courses
Content-Type: application/json

{
    "name": "Javascript",
    "hours": 35
}
###
POST https://628b9617667aea3a3e3289a2.mockapi.io/api/courses
Content-Type: application/json

{
    "name": "Vue",
    "hours": 40
}
